### PR TITLE
Fix to correctly parse single quotes found in a double quote strings

### PR DESCRIPTION
**Pull request by aiampogi**
### Issue Summary

Tags with single quotes inside double quotes doesn't get parsed/truncated correctly according to the limit (by words/characters)
### Steps to Reproduce

`ddownsize('<p>Let\'s get in!</p><p>hello world</p>', {words:"1"});`
results to:
`'<p>Let\'s get in!</p><p>hello world</p></p>'`

But it should result to:
`'<p>Let's get in!</p><p>hello</p>'`

This is a bug because the specified number of html words should be followed even if the alt text of the  has a single quote/apostrophe.
### Technical details
- Client OS: Windows 8
- Server OS: Windows 8
- Node Version: v0.10.24
- Browser: Chrome

directly related to: https://github.com/TryGhost/Ghost/issues/2106

### CODE REVIEW

**Comment by aiampogi** [comment]
closed issue number 7 and opened this pull request instead

**Comment by cgiffard** [comment]
Thanks! Reviewing now.

**Comment by cgiffard** [comment]
I did a manual merge. Thanks again!

**Comment by aiampogi** [comment]
Glad to help!

**Pull request merged**
