### PR TITLE
bug fixes and cleanup.

### LINKED ISSUE #14: trailing tags in character mode.
```
it("should not have trailing empty tags", function () {
downsize("<p>characters</p><i>what</i>", {characters: 10})
.should.equal("<p>characters</p>");
});
```

This fails with an extra `<i></i>` just as words mode did before https://github.com/zethraeus/Downsize/commit/5568bfe68d050e3073168daaf18da77a43cb8d9b

i have not further researched why.

### PR DESCRIPTION
**Pull request by adam-zethraeus**
I want to put this up for PR despite having collab status because it makes some stylistic changes, and i don't want to step on your toes. :)
(the changes are a bit less deep than the line count implies, there's a bit of reordering and renaming)

it fixes:
- zero word truncation bug
- trailing tags in char mode bug

notable changes:
- i've tried to make the state more explicit (grouped into trackedState and options objs)
- introduces more explicit mode for chars vs words
- i've separated limit checking and counting into two different functions
- limit checking now happens first (which is what fixes https://github.com/cgiffard/Downsize/issues/14 and allows for removal of the 'characters + 1' thing)

i hope it's alright. lmk.

### CODE REVIEW

**Comment by cgiffard** [comment]
Thanks — whoah that's a heck of a PR. :) I'll have a look when I get to work.

**Comment by cgiffard** [comment]
So far, I really like this! Thanks for keeping me in the loop by filing this as a PR rather than just pushing to master.

I haven't had an opportunity to do a proper review, but I'll try get it done ASAP so we can get this in. :)

Thanks again!

**Comment by adam-zethraeus** [comment]
Could you give an ETA on this / maybe just a general assurance that it's ok for me to develop on top of these changes?

**Comment by adam-zethraeus** [comment]
ping?

**Comment by cgiffard** [comment]
Sorry, this one slipped. I figure you can merge it — it looks good! Let me know when you've done it, I'll push an update to npm.

FYI the general direction I want to take this is:
- Anything can be theoretically counted — so we need to maintain an arbitrary 'count' function.
- We want to maintain a proper state machine for parsing, with no lookahead if possible. No regex or anything should be ever used in parsing input, except for detecting character ranges.
- I want this to eventually work with streaming input. (hence no lookahead.)

Does that sound reasonable — have I missed anything? :)

**Comment by adam-zethraeus** [comment]
all in, ready to npm.

direction makes sense! I have no idea if the streaming input with no lookahead is viable. Does that necessitate a char being released for every one coming in?

I don't know when I'll do it, but my next push will be to try to build some sort of special case handling in for the ghost image thing, but as generically as possible. I'll look at making count generic and implementing block counting after that.

**Pull request merged**
