### PR TITLE
Rounding reverts

### PR DESCRIPTION
**Pull request by adam-zethraeus**
As discussed at https://github.com/cgiffard/Downsize/issues/23, and since it's been a few days.

Please take a look at the context, @cgiffard @remy.

(Once this is in i'm going to redo the contexttualtags ghost PR, since it's unblocked now)

### CODE REVIEW

**Comment by remy** [comment]
:thumbsup:

**Comment by cgiffard** [comment]
I'm cool for you to merge as long as we can keep `round:true` or a similarly simple flag. I liked that. :)

**Comment by adam-zethraeus** [comment]
I'll add that to this PR before merge. Thanks guys.

**Comment by cgiffard** [comment]
No, I'm really sorry I didn't do due diligence before merging! I wasted you guys' time — apologies for that. I'll make sure I'm doing a more thorough code review in future.

**Comment by adam-zethraeus** [comment]
also, props to @remy for pushing downsize in a good direction :) (you should stick around here if there's other stuff you'd like to help improve!)

**Comment by adam-zethraeus** [comment]
https://github.com/cgiffard/Downsize/issues/25

**Pull request merged**
